# 大师兄影视去广告
DOMAIN,c.tobidad.cn
DOMAIN,mi.gdt.qq.com
DOMAIN,win.gdt.qq.com
DOMAIN,sdk.e.qq.com
DOMAIN,gdfp.gifshow.com
DOMAIN,tm.sigmob.cn
DOMAIN,rtbcallback.sigmob.cn
DOMAIN,adservice.sigmob.cn
DOMAIN,open.e.kuaishou.com